version: '{build}'
branches:
  only:
  - master
# clone_folder: C:/projects/bfa
image:
  - Visual Studio 2017
#  - Ubuntu
configuration: Release
platform: x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
  - TARGET_PLATFORM: x64
  
matrix:
  fast_finish: true
  exclude:
    - image: Ubuntu
      TARGET_PLATFORM: x86

# skip unsupported combinations
init:
  - ps: |
      If ($isLinux) {
        $env:APPVEYOR_CACHE_SKIP_RESTORE = "true"
        $env:APPVEYOR_CACHE_SKIP_SAVE = "true"
      }
  - cmd: |
      set arch=
      if "%TARGET_PLATFORM%"=="x64" ( set arch= Win64)
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu" ( set generator="Unix Makefiles" )
      echo %generator%

install:
- sh: cmake

build_script:
  - cmd: |
      git clone git://git.blender.org/blender.git %APPVEYOR_BUILD_FOLDER%
      git submodule update --init --recursive
      git submodule foreach git checkout master
      git submodule foreach git pull --rebase origin master
      if "%TARGET_PLATFORM%"=="x86" (svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14 ../lib/windows_vc14)
      if "%TARGET_PLATFORM%"=="x64" (svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 ../lib/win64_vc14)
      mkdir build
      cd build
      cmake --version
      cmake . -G %generator% -DCMAKE_BUILD_TYPE=Release ..
      cmake --build . --target PACKAGE
after_build:
  - '7z a biud.zip %APPVEYOR_BUILD_FOLDER%\build\'
  
artifacts:
  -
    path: biud.zip
    name: Binari


