version: '{build}'
branches:
  only:
  - master
# clone_folder: C:/projects/bfa
image:
  - Visual Studio 2019
#  - Ubuntu
configuration: Release
platform: x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
  - TARGET_PLATFORM: x64
  
matrix:
  fast_finish: true
  exclude:
    - image: Ubuntu
      TARGET_PLATFORM: x86

# skip unsupported combinations
init:
  - ps: |
      If ($isLinux) {
        $env:APPVEYOR_CACHE_SKIP_RESTORE = "true"
        $env:APPVEYOR_CACHE_SKIP_SAVE = "true"
      }
  - cmd: |
      set arch=
      if "%TARGET_PLATFORM%"=="x64" ( set arch= Win64)
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 15 2019%arch%" )
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
      If "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu" ( set generator="Unix Makefiles" )
      echo %generator%

install:
- sh: cmake

build_script:
  - cmd: |
      md bld
      cd bld
      md blender
      cd blender
      git clone git://git.blender.org/blender.git %APPVEYOR_BUILD_FOLDER%\bld\blender

      svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15 ../lib/win64_vc15 >>..\..\xx.txt
      make.bat full nobuild
after_build:
  - '7z a -mqs -ms=on %APPVEYOR_BUILD_FOLDER%\bld\build_windows_Full_x64_vc16_Release %APPVEYOR_BUILD_FOLDER%\biud.7z'
  
artifacts:
  -
    path: biud.7z
    name: Binari


