# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: prep
        run: |
          C:
          cd /
          md "Program Files\NVIDIA GPU Computing Toolkit\CUDA"
          md bld
          cd bld
          md cuda
          md lib
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/cud.7z -OutFile cud.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/blender.7z -OutFile blender.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/win64_vc15.7z -OutFile win64_vc15.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/ph1.7z -OutFile ph1.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/ph2.zip -OutFile ph2.zip
          
          7z x cud.7z -oC:\bld\cuda\ -spf
          
          7z x win64_vc15.7z -oC:\bld\lib\ -spf
          7z x blender.7z -spf
          7z x ph1.7z -spf -aoa
          7z x ph2.zip -spf -aoa
          

          cd C:\bld\blender
          dir > C:\bld\logg.txt
          echo "::add-path::C:\bld\cuda\nvvm\bin;C:\bld\cuda\bin"
        
      - name: logs1
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cdlog
          path: C:\bld\logg.txt
         
      - name: mkklink
        if: always()
        shell: cmd
        run: |
          mklink /J "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" C:\bld\cuda
          mklink /J "C:\zwant" C:\bld\build_windows_Bpy_x64_vc16_Release
          # C:\bld\build_windows_x64_vc16_Release
        
      - name: nvccv
        if: always()
        run: nvcc -V
        env:
          CUDACXX: C:\bld\cuda\bin
          CMAKE_CUDA_COMPILER: C:\bld\cuda\bin
          CUDA_TOOLKIT_ROOT_DIR: C:\bld\cuda
          CUDA_PATH: C:\bld\cuda
          CUDA_PATH_V10_1: C:\bld\cuda
          CUDA_PATH_V10_2: C:\bld\cuda
      
      - name: Build
        if: always()
        shell: cmd
        run: C:\bld\blender\make.bat bpy
        env:
          CUDACXX: C:\bld\cuda\bin
          CMAKE_CUDA_COMPILER: C:\bld\cuda\bin
          CUDA_TOOLKIT_ROOT_DIR: C:\bld\cuda
          CUDA_PATH: C:\bld\cuda
          CUDA_PATH_V10_1: C:\bld\cuda
          CUDA_PATH_V10_2: C:\bld\cuda
        
      - name: logs2
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bldlog
          path: C:\zwant\Build.log
        
      - name: ziping
        if: always()
        run: 7z a C:\bld\biud.7z "C:\zwant" -mqs -ms=on
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v2
        with:
          title: Bltezt
            - files:[C:\bld\biud.7z]
          
          
        
      - name: logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: chklog
          path: C:\bld\logg.txt
