# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: prep
        run: |
          pip install ninja
          C:
          md C:\blender-git
          cd C:\blender-git
          git clone https://projects.blender.org/blender/blender.git
          cd C:\blender-git\blender
          make update
          make ninja
        

                
      - name: ziping
        if: always()
        run: 7z a C:\llvmbd.7z C:\blender-git\build_windows
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ninjpf
          path: C:\llvmbd.7z
          compression-level: 0
