# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      # Runs a set of commands using the runners shell
      - name: prep
        run: |
          C:
          cd /
          md bld
          cd bld
          md lib
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/blender.7z -OutFile blender.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/win64_vc15.7z -OutFile win64_vc15.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/ph1.7z -OutFile ph1.7z
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/ph2.zip -OutFile ph2.zip
          
          7z x win64_vc15.7z -oC:\bld\lib\ -spf
          7z x blender.7z -spf
          7z x ph1.7z -spf -aoa
          7z x ph2.zip -spf -aoa

          cd C:\bld\blender
          dir > C:\bld\logg.txt
        
      - name: logs1
        uses: actions/upload-artifact@v2
        with:
          name: cdlog
          path: C:\bld\logg.txt
        
      - name: Build
        run: C:\bld\blender\make.bat > C:\bld\logg.txt
        shell: cmd
        
      - name: ziping
        run: 7z a C:\bld\biud.7z -mqs -ms=on -ir!C:\bld\*.obj -ir!C:\bld\*.exe -ir!C:\bld\*.pdb -ir!C:\bld\*.lib
          
      - name: uploadexe
        uses: actions/upload-artifact@v2
        with:
          name: Bltezt
          path: C:\bld\biud.7z
          
        
      - name: logs   
        uses: actions/upload-artifact@v2
        with:
          name: chklog
          path: C:\bld\logg.txt
