# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      # Runs a set of commands using the runners shell
      - name: Buid
        run: |
          C:
          cd /
          md bld
          cd bld
          md lib
          curl -L https://github.com/Klanly/bleeda/releases/download/1.02/blender.7z -o blender.7z
          curl -L https://github.com/Klanly/bleeda/releases/download/1.02/win64_vc15.7z -o win64_vc15.7z
          7z e blender.7z -oC:\bld\
          7z e win64_vc15.7z -oC:\bld\lib\
          cd blender
          make.bat > C:\bld\logg.txt
          7z a C:\bld\biud.7z -mqs -ms=on -ir!C:\bld\*.obj -ir!C:\bld\*.exe -ir!C:\bld\*.pdb -ir!C:\bld\*.lib
      - uses: actions/upload-artifact@v2
        with:
          name: Bltezt
          path: C:\bld\biud.7z
         
      - uses: actions/upload-artifact@v2
        with:
          name: chklog
          path: C:\bld\logg.txt
